#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU1                               100
#define IDD_DIALOG_DEBUG                        103
#define IDD_DIALOG_SERIAL_CFG                   104
#define IDD_DIALOG_CPU_SPEED                    106
#define IDD_DIALOG_SOUND_CFG                    108
#define IDM_RESET                               40000
#define IDM_QUIT                                40001
#define IDM_SCALE_X1                            40002
#define IDM_SCALE_X2                            40003
#define IDM_TEXT_CGA                            40004
#define IDM_TEXT_VGA_8x16                       40005
#define IDM_SET_SPEED                           40006
#define IDM_SAVE_CONFIGURATION                  40008
#define IDM_LOAD_CONFIGURATION                  40009
#define IDM_SAVE_DEFAULT_CONFIGURTION           40010
#define IDM_SET__FD_IMAGE                       40011
#define IDM_SET__HD_IMAGE                       40012
#define IDM_SET_SERIAL_PORTS                    40013
#define IDM_START_DEBUGGER                      40014
#define IDM_CONFIGURE_SOUND                     40015
#define IDC_EDIT_CS                             40101
#define IDC_EDIT_SS                             40102
#define IDC_EDIT_DS                             40103
#define IDC_EDIT_ES                             40104
#define IDC_EDIT_AX                             40105
#define IDC_EDIT_BX                             40106
#define IDC_EDIT_CX                             40107
#define IDC_EDIT_DX                             40108
#define IDC_EDIT_SP                             40109
#define IDC_EDIT_BP                             40110
#define IDC_EDIT_SI                             40111
#define IDC_EDIT_DI                             40112
#define IDC_MEMORY_ADDRESS                      40114
#define IDC_DISASS_ADDRESS                      40115
#define IDC_BRK_SET                             40116
#define IDC_BRK_CLR                             40117
#define IDC_BRK_CLR_ALL                         40118
#define IDC_ENABLE_TRACE                        40119
#define IDC_DUMP_TRACE                          40120
#define IDC_STATIC_FLAGS                        40130
#define IDC_LIST_MEMORY                         40131
#define IDC_LIST_ASM                            40132
#define IDC_DEBUG_STEP                          40133
#define IDC_DEBUG_CONTINUE                      40134
#define IDC_COMBO_COM1                          40201
#define IDC_COMBO_COM2                          40202
#define IDC_COMBO_COM3                          40203
#define IDC_COMBO_COM4                          40204
#define IDC_EDIT_COM1_ADDR                      40211
#define IDC_EDIT_COM2_ADDR                      40212
#define IDC_EDIT_COM3_ADDR                      40213
#define IDC_EDIT_COM4_ADDR                      40214
#define IDC_EDIT_COM1_PORT                      40221
#define IDC_EDIT_COM2_PORT                      40222
#define IDC_EDIT_COM3_PORT                      40223
#define IDC_EDIT_COM4_PORT                      40224
#define IDC_CPU_SPEED_COMBO                     40305
#define IDC_ENABLE_PC_SPEAKER                   40400
#define IDC_SAMPLE_RATE_COMBO                   40401
#define IDC_VOLUME_SLIDER                       40402
#define IDC_VOLUME_STATIC                       40403
